# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ScratchPad-UILibraries' do

pod 'VBFPopFlatButton'

end

target 'ScratchPad-UILibrariesTests' do

end

